
# push할때 / issue 생성될때 / 수동으로 트리거 할떄 job 실행
name: multiple-event-worklfow
on:
  push:
  issues:
    types:  [opened]
  workflow_dispatch:

jobs:
  multiple-event-job: 
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world
      - name: step 2
        run: |
          echo hello world
          echo gtihub action
    
