name: pull-request-workflow 14
on: push 

jobs:
  pull-request-job: 
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world
      - name: step 2
        run: |
          echo hello world
          echo gtihub action
        
