name: workflow-dispatch
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'set name'
        required: true
        default: 'github-actions'
        type: string
      environment: 
        description: 'set env' 
        required: true
        default: 'dev'
        type: 'choice'
        options:
        - dev
        - qa
        - prod


#description: name에 대한 설명
#required: 필수값 여부
#default: 기본값
#type: 타입 

# 위에서 설정한 값들을 밑에 jobs에서 사용 가능
jobs:
  workflow-dispatch-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world
      - name: step 2
        run: |
          echo hello world
          echo gtihub action
      - name: echo inputs
        run: |
          echo ${{inputs.name}}
          echo ${{inputs.environment}}
  

        
        
