name: artifact
on:
  push:

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo hello-world > hello.txt  # hello.txt 안에 hello-world 들어가도록 설정
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact-test
          path: hello.txt    # 생성된 hello.txt 파일을 artifact-test라는 artifact로 업로드함

  download-artifact:
    runs-on: ubuntu-latest
    needs: [upload-artifact]
    steps:
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact-test # 이 이름의 artifact를 다운로드함
          path: ./  # 루트 path
      - name: check
        run: cat hello.txt
