# 해당 path에 변경사항이 있으면 job 실행
name: path-filter
on:
  push:
    paths:
    - '.github/workflows/part1/*'
    - '!.github/workflows/part1/push.yml'  #제외 한다는뜻
jobs:
  path-filter:
    runs-on: ubuntu-latest
    steps:
    - name: echo
      run: echo hello
