name: timeout
on: push

jobs:
  timeout:
    runs-on: ubuntu-latest
    timeout-minutes: 2 # 2분 후에 종료
    steps:
      - name: loop
        run: |
          count=0
          while true; do
            echo "seconds: $count"
            count=$((count+1))
            sleep 1
          done
        timeout-minutes: 1  # 첫번째 step이 1분안에 종료 안돼면 두번째 스텝은 실행 안댐  
      - name: echo
        run: echo hello
