name: output
on: push


jobs:
  create-output:
    runs-on: ubuntu-latest
    steps:
    - name: echo output
      id: check-output  # id 값으로 구분한다 , key값은 같아도 상관 없음, 하나의 job에 중복 되지 않아야함
      run: |   # key = hello  value =hello 인 OutPut
        echo "test=hello" >> $GITHUB_OUTPUT     
    - name: check output
      run: | # steps.id값.outputs.key값
        echo ${{ steps.check-output.outputs.test }}    

  