name: timeout
on: push

jobs:
  timeout:
    runs-on: ubuntu-latest
    timeout-minutes: 2 # 2분되면 종료
    steps:
    - name: loop
      run: |
        count=0
        while true; do
          ech "seconds: $count"
          count=$((count+1))
          sleep 1
        done
    - name: echo
      run: echo hello      
          